// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/raymondgitonga/matching-server/internal/core/dormain"
	"github.com/raymondgitonga/matching-server/internal/core/service"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ service.Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			GetPartnerFunc: func(ctx context.Context, partnerID int) (*dormain.Partner, error) {
//				panic("mock out the GetPartner method")
//			},
//			GetPartnersFunc: func(ctx context.Context, speciality string) (*[]dormain.Partner, error) {
//				panic("mock out the GetPartners method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// GetPartnerFunc mocks the GetPartner method.
	GetPartnerFunc func(ctx context.Context, partnerID int) (*dormain.Partner, error)

	// GetPartnersFunc mocks the GetPartners method.
	GetPartnersFunc func(ctx context.Context, speciality string) (*[]dormain.Partner, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetPartner holds details about calls to the GetPartner method.
		GetPartner []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// PartnerID is the partnerID argument value.
			PartnerID int
		}
		// GetPartners holds details about calls to the GetPartners method.
		GetPartners []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Speciality is the speciality argument value.
			Speciality string
		}
	}
	lockGetPartner  sync.RWMutex
	lockGetPartners sync.RWMutex
}

// GetPartner calls GetPartnerFunc.
func (mock *RepositoryMock) GetPartner(ctx context.Context, partnerID int) (*dormain.Partner, error) {
	if mock.GetPartnerFunc == nil {
		panic("RepositoryMock.GetPartnerFunc: method is nil but Repository.GetPartner was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		PartnerID int
	}{
		Ctx:       ctx,
		PartnerID: partnerID,
	}
	mock.lockGetPartner.Lock()
	mock.calls.GetPartner = append(mock.calls.GetPartner, callInfo)
	mock.lockGetPartner.Unlock()
	return mock.GetPartnerFunc(ctx, partnerID)
}

// GetPartnerCalls gets all the calls that were made to GetPartner.
// Check the length with:
//
//	len(mockedRepository.GetPartnerCalls())
func (mock *RepositoryMock) GetPartnerCalls() []struct {
	Ctx       context.Context
	PartnerID int
} {
	var calls []struct {
		Ctx       context.Context
		PartnerID int
	}
	mock.lockGetPartner.RLock()
	calls = mock.calls.GetPartner
	mock.lockGetPartner.RUnlock()
	return calls
}

// GetPartners calls GetPartnersFunc.
func (mock *RepositoryMock) GetPartners(ctx context.Context, speciality string) (*[]dormain.Partner, error) {
	if mock.GetPartnersFunc == nil {
		panic("RepositoryMock.GetPartnersFunc: method is nil but Repository.GetPartners was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Speciality string
	}{
		Ctx:        ctx,
		Speciality: speciality,
	}
	mock.lockGetPartners.Lock()
	mock.calls.GetPartners = append(mock.calls.GetPartners, callInfo)
	mock.lockGetPartners.Unlock()
	return mock.GetPartnersFunc(ctx, speciality)
}

// GetPartnersCalls gets all the calls that were made to GetPartners.
// Check the length with:
//
//	len(mockedRepository.GetPartnersCalls())
func (mock *RepositoryMock) GetPartnersCalls() []struct {
	Ctx        context.Context
	Speciality string
} {
	var calls []struct {
		Ctx        context.Context
		Speciality string
	}
	mock.lockGetPartners.RLock()
	calls = mock.calls.GetPartners
	mock.lockGetPartners.RUnlock()
	return calls
}
